"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useKineStore } from "@/store/useKineStore";
import { buildWeek } from "@/lib/week-builder";
import type { WeekData, WeekDay } from "@/lib/week-builder";
import { DAY_LABELS } from "@/data/constants";
import { getCurrentPhase } from "@/lib/cycle";
import { getCurrentPhase as getTrainingPhase } from "@/lib/periodisation";
import Button from "@/components/Button";
import BottomSheet from "@/components/BottomSheet";
import SessionRearrange from "@/components/SessionRearrange";
import { toast } from "@/components/Toast";
import Link from "next/link";

const LOADING_MESSAGES = [
  "Analysing your training profile…",
  "Building your session structure…",
  "Selecting exercises for your equipment…",
  "Balancing volume and recovery…",
  "Finalising your programme…",
];

export default function AppHome() {
  const { weekData, setWeekData, goal, progressDB } = useKineStore();
  const [loading, setLoading] = useState(false);
  const [loadingMsg, setLoadingMsg] = useState(0);
  const router = useRouter();

  // If no goal set, redirect to onboarding
  useEffect(() => {
    if (!goal) {
      router.replace("/app/onboarding");
    }
  }, [goal, router]);

  // Rotate loading messages
  useEffect(() => {
    if (!loading) return;
    const interval = setInterval(() => {
      setLoadingMsg((prev) => (prev + 1) % LOADING_MESSAGES.length);
    }, 3000);
    return () => clearInterval(interval);
  }, [loading]);

  async function handleBuildWeek() {
    setLoading(true);
    setLoadingMsg(0);

    const result = await buildWeek();

    if (result.weekData) {
      setWeekData(result.weekData);
    }

    if (!result.success && result.error) {
      toast(result.error, "error");
    }

    setLoading(false);
  }

  if (!goal) return null;

  // No week data yet — show build prompt
  if (!weekData) {
    return (
      <div className="flex min-h-[60vh] flex-col items-center justify-center text-center">
        {loading ? (
          <>
            <div className="h-8 w-8 animate-spin rounded-full border-2 border-accent border-t-transparent" />
            <p className="mt-4 text-sm text-muted2 animate-pulse">
              {LOADING_MESSAGES[loadingMsg]}
            </p>
          </>
        ) : (
          <>
            <h2 className="font-display text-2xl tracking-wide text-text">
              Ready to build your week
            </h2>
            <p className="mt-2 text-sm text-muted2">
              Your personalised training programme will be generated by AI.
            </p>
            <Button className="mt-6" size="lg" onClick={handleBuildWeek}>
              Build Week {progressDB.currentWeek || 1} →
            </Button>
          </>
        )}
      </div>
    );
  }

  // Show week view
  const week = weekData as WeekData;

  return <WeekView week={week} onRebuild={handleBuildWeek} loading={loading} />;
}

// ── Week View ──

function WeekView({
  week,
  onRebuild,
  loading,
}: {
  week: WeekData;
  onRebuild: () => void;
  loading: boolean;
}) {
  const { cycleType, cycle, setCycle, progressDB } = useKineStore();
  const [showRearrange, setShowRearrange] = useState(false);
  const today = new Date().getDay();
  const todayIdx = today === 0 ? 6 : today - 1;
  const weekStart = getWeekDateRange();
  const trainingPhase = getTrainingPhase(progressDB.currentWeek, progressDB.phaseOffset);

  // Cycle phase
  const phase = cycleType === "regular"
    ? getCurrentPhase(cycle.periodLog, cycle.avgLength)
    : null;

  return (
    <div>
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center justify-between">
          <p className="text-[10px] tracking-[0.3em] text-accent uppercase">
            Week {week._weekNum || 1} · {weekStart}
          </p>
          <Link href="/app/calendar" className="text-[10px] text-muted2 hover:text-accent transition-colors">
            Calendar →
          </Link>
        </div>
        <h1 className="mt-1 font-display text-2xl tracking-wide text-text">
          {week.programName}
        </h1>
        {week._isFallback && (
          <p className="mt-1 text-[10px] text-muted uppercase tracking-wider">
            Standard programme — AI will personalise next time
          </p>
        )}
        <div className="mt-1 flex items-center gap-2">
          <span className="rounded-full bg-surface2 px-2 py-0.5 text-[10px] text-muted2">
            {trainingPhase.label} · {trainingPhase.weekInPhase}/{trainingPhase.totalWeeksInPhase}
          </span>
        </div>
      </div>

      {/* Cycle phase + #13: Period quick-log */}
      {phase && (
        <div className="mb-4 rounded-[var(--radius-default)] border border-border bg-surface p-3">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-text">◐ {phase.label} phase · Day {phase.day}</span>
            <button
              onClick={() => {
                const today = new Date().toISOString().split("T")[0];
                const lastLog = cycle.periodLog[cycle.periodLog.length - 1];
                const type = lastLog?.type === "start" ? "end" : "start";
                setCycle({
                  ...cycle,
                  periodLog: [...cycle.periodLog, { date: today, type }],
                });
                toast(`Period ${type} logged`, "success");
              }}
              className="text-[10px] text-accent hover:underline"
            >
              Log period {cycle.periodLog[cycle.periodLog.length - 1]?.type === "start" ? "end" : "start"}
            </button>
          </div>
          <p className="mt-1 text-[10px] text-muted2">{phase.trainingNote}</p>
        </div>
      )}
      {/* Period quick-log when no cycle phase (cycle type is regular but no log yet) */}
      {cycleType === "regular" && !phase && (
        <div className="mb-4 rounded-[var(--radius-default)] border border-border/50 bg-surface/50 p-3">
          <div className="flex items-center justify-between">
            <span className="text-xs text-muted2">No period logged yet</span>
            <button
              onClick={() => {
                const today = new Date().toISOString().split("T")[0];
                setCycle({
                  ...cycle,
                  periodLog: [...cycle.periodLog, { date: today, type: "start" }],
                });
                toast("Period start logged", "success");
              }}
              className="text-[10px] text-accent hover:underline"
            >
              Log period start
            </button>
          </div>
        </div>
      )}

      {/* Coach note */}
      {week.weekCoachNote && (
        <div className="mb-6 rounded-[var(--radius-default)] border border-border bg-surface p-4">
          <p className="text-xs leading-relaxed text-muted2">
            {week.weekCoachNote}
          </p>
        </div>
      )}

      {/* Gap reentry */}
      {(() => {
        const lastSession = (progressDB.sessions as { date?: string }[]).slice(-1)[0];
        if (lastSession?.date) {
          const daysSince = Math.floor((Date.now() - new Date(lastSession.date).getTime()) / (1000 * 60 * 60 * 24));
          if (daysSince >= 7) {
            return (
              <div className="mb-4 rounded-[var(--radius-default)] border border-accent/30 bg-accent-dim p-4">
                <p className="text-sm font-medium text-text">Welcome back</p>
                <p className="text-xs text-muted2 mt-1">
                  It&apos;s been {daysSince} days. {progressDB.sessions.length} session{progressDB.sessions.length > 1 ? "s" : ""} completed so far.
                  No guilt — just pick up where you left off.
                </p>
              </div>
            );
          }
          if (daysSince >= 4) {
            return (
              <div className="mb-4 rounded-[var(--radius-default)] border border-border bg-surface p-3">
                <p className="text-xs text-muted2">
                  {daysSince} days since your last session. Ready when you are.
                </p>
              </div>
            );
          }
        }
        return null;
      })()}

      {/* Session completion summary */}
      {(() => {
        const weekSessions = (progressDB.sessions as { weekNum?: number }[])
          .filter((s) => s.weekNum === progressDB.currentWeek);
        const trainingDayCount = week.days.filter((d) => !d.isRest).length;
        if (weekSessions.length > 0 && weekSessions.length < trainingDayCount) {
          return (
            <p className="mb-3 text-xs text-muted2">
              {weekSessions.length}/{trainingDayCount} sessions done this week
            </p>
          );
        }
        if (weekSessions.length >= trainingDayCount && trainingDayCount > 0) {
          return (
            <div className="mb-4 rounded-[var(--radius-default)] border border-accent/30 bg-accent-dim p-3 text-center">
              <p className="text-xs text-accent font-medium">Week {progressDB.currentWeek} complete</p>
            </div>
          );
        }
        return null;
      })()}

      {/* Days */}
      {(() => {
        // Find next active session (first non-rest, non-completed, today or future)
        const nextActiveIdx = week.days.findIndex((d, i) => {
          if (d.isRest) return false;
          const completed = (progressDB.sessions as { weekNum?: number; dayIdx?: number }[])
            .some((s) => s.weekNum === progressDB.currentWeek && s.dayIdx === i);
          return !completed && i >= todayIdx;
        });

        return (
          <div className="flex flex-col gap-2">
            {week.days.map((day, i) => {
              const isCompleted = (progressDB.sessions as { weekNum?: number; dayIdx?: number }[])
                .some((s) => s.weekNum === progressDB.currentWeek && s.dayIdx === i);
              const isPast = i < todayIdx;
              const isNextActive = i === nextActiveIdx;

              return (
                <DayCard
                  key={i} day={day} dayIdx={i}
                  isToday={i === todayIdx}
                  isCompleted={isCompleted}
                  isPast={isPast}
                  expanded={isNextActive || i === todayIdx}
                />
              );
            })}
          </div>
        );
      })()}

      {/* Actions */}
      <div className="mt-8 flex justify-center gap-3">
        <Link href="/app/week-checkin" className="inline-flex items-center rounded-[var(--radius-default)] px-3 py-1.5 text-xs text-muted2 hover:text-text hover:bg-surface2 transition-all">
          Check-in
        </Link>
        <Button variant="ghost" size="sm" onClick={() => setShowRearrange(true)}>
          Rearrange
        </Button>
        <Button variant="ghost" size="sm" onClick={onRebuild} disabled={loading}>
          {loading ? "Rebuilding…" : "Regenerate"}
        </Button>
      </div>

      <SessionRearrange open={showRearrange} onClose={() => setShowRearrange(false)} />
    </div>
  );
}

// ── Day Card ──

// ── Rest day recovery messages ──
const REST_DAY_MESSAGES = [
  "Your muscles grow during rest, not during training.",
  "Recovery is where the work becomes results.",
  "Active recovery — a walk, stretch, or gentle movement helps.",
  "Sleep and nutrition do the heavy lifting today.",
  "Rest days prevent injury and keep you consistent long-term.",
  "Trust the process — rest is part of the programme.",
];

function getRestMessage(dayIdx: number): string {
  return REST_DAY_MESSAGES[dayIdx % REST_DAY_MESSAGES.length];
}

function DayCard({ day, dayIdx, isToday, isCompleted = false, isPast = false, expanded = false }: {
  day: WeekDay; dayIdx: number; isToday: boolean; isCompleted?: boolean; isPast?: boolean; expanded?: boolean;
}) {
  const router = useRouter();
  const { progressDB, setProgressDB } = useKineStore();
  const [showSessionReview, setShowSessionReview] = useState(false);
  const dayLabel = DAY_LABELS[(day.dayNumber - 1) % 7];

  // Find completed session log for this day
  const completedSession = isCompleted
    ? (progressDB.sessions as { weekNum?: number; dayIdx?: number; logs?: Record<number, { name: string; actual: { reps: string; weight: string }[]; note?: string; saved?: boolean }>; effort?: number; soreness?: number; title?: string }[])
        .find((s) => s.weekNum === progressDB.currentWeek && s.dayIdx === dayIdx)
    : null;

  if (day.isRest) {
    return (
      <div
        className={`rounded-[var(--radius-default)] border px-4 py-3 ${
          isToday ? "border-accent/30 bg-accent-dim"
          : isPast ? "border-border/30 bg-surface/30 opacity-60"
          : "border-border/50 bg-surface/50"
        }`}
      >
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-xs font-medium text-muted2">{dayLabel}</span>
            {isToday && (
              <span className="rounded-full bg-accent/20 px-2 py-0.5 text-[10px] text-accent">
                Today
              </span>
            )}
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs text-muted">Rest & Recovery</span>
            {!isPast && (
              <button
                onClick={() => router.push(`/app/custom-builder?day=${dayIdx}`)}
                className="text-[10px] text-muted2 hover:text-accent transition-colors"
              >
                + add session
              </button>
            )}
          </div>
        </div>
        {/* #9: Rest day recovery message */}
        {(isToday || (!isPast && expanded)) && (
          <p className="mt-2 text-[10px] text-muted font-light leading-relaxed">
            {getRestMessage(dayIdx)}
          </p>
        )}
      </div>
    );
  }

  return (
    <div
      className={`rounded-[var(--radius-default)] border p-4 transition-all ${
        isCompleted ? "border-accent/30 bg-accent-dim/30"
        : isToday ? "border-accent bg-surface"
        : isPast ? "border-border/50 bg-surface/50 opacity-60"
        : "border-border bg-surface hover:border-border-active"
      }`}
    >
      {/* Day header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-xs font-medium text-muted2">{dayLabel}</span>
          {isToday && (
            <span className="rounded-full bg-accent/20 px-2 py-0.5 text-[10px] text-accent">
              Today
            </span>
          )}
          {isCompleted && (
            <span className="rounded-full bg-accent/20 px-2 py-0.5 text-[10px] text-accent">
              ✓ done
            </span>
          )}
        </div>
        <span className="text-[10px] text-muted">{day.sessionDuration}</span>
      </div>

      {/* Title */}
      <h3 className="mt-2 font-display text-lg tracking-wide text-text">
        {day.sessionTitle}
      </h3>

      {/* Collapsed: summary with context */}
      {!expanded && (
        <div className="mt-1">
          <div className="flex items-center justify-between">
            <p className="text-[11px] text-muted2 font-light truncate flex-1">
              {day.exercises.length} exercises · {day.sessionDuration}
            </p>
            <button onClick={() => router.push(`/app/pre-session?day=${dayIdx}`)}
              className="text-[10px] text-accent hover:underline shrink-0 ml-2">View →</button>
          </div>
          {day.coachNote && (
            <p className="mt-1 text-[10px] text-muted font-light truncate">{day.coachNote}</p>
          )}
          <div className="mt-1.5 flex flex-wrap gap-1">
            {day.exercises.slice(0, 3).map((ex, i) => (
              <span key={i} className="text-[9px] text-muted2 bg-surface2/50 rounded px-1.5 py-0.5">{ex.name}</span>
            ))}
            {day.exercises.length > 3 && (
              <span className="text-[9px] text-muted">+{day.exercises.length - 3}</span>
            )}
          </div>
        </div>
      )}

      {/* Expanded: full details */}
      {expanded && (
        <>
          {day.coachNote && <p className="mt-1 text-xs text-muted2">{day.coachNote}</p>}
          <div className="mt-3 flex flex-col gap-1">
            {day.exercises.map((ex, i) => (
              <div key={i} className="flex items-center justify-between text-xs">
                <span className="text-text/80">{ex.name}</span>
                <span className="text-muted">{ex.sets}×{ex.reps}</span>
              </div>
            ))}
          </div>
          <div className="mt-4 flex gap-2">
            {isCompleted ? (
              <>
                <Button className="flex-1" size="sm" variant="secondary"
                  onClick={() => setShowSessionReview(true)}>
                  View results
                </Button>
                <Button className="flex-1" size="sm" variant="ghost"
                  onClick={() => router.push(`/app/pre-session?day=${dayIdx}`)}>
                  Redo
                </Button>
              </>
            ) : (
              <Button className="w-full" size="sm" variant={isToday ? "primary" : "secondary"}
                onClick={() => router.push(`/app/pre-session?day=${dayIdx}`)}>
                {isToday ? "Start session" : "View session"}
              </Button>
            )}
          </div>
        </>
      )}

      {/* #6: Session replay/amendment bottom sheet */}
      {completedSession && (
        <SessionReviewSheet
          open={showSessionReview}
          onClose={() => setShowSessionReview(false)}
          session={completedSession}
          dayIdx={dayIdx}
        />
      )}
    </div>
  );
}

// ── Session Review/Edit Sheet ──

function SessionReviewSheet({ open, onClose, session, dayIdx }: {
  open: boolean;
  onClose: () => void;
  session: { logs?: Record<number, { name: string; actual: { reps: string; weight: string }[]; note?: string; saved?: boolean }>; effort?: number; soreness?: number; title?: string; weekNum?: number; dayIdx?: number };
  dayIdx: number;
}) {
  const { progressDB, setProgressDB } = useKineStore();
  const [editing, setEditing] = useState(false);
  const [editLogs, setEditLogs] = useState<Record<string, { reps: string; weight: string }[]>>({});

  const logs = session.logs || {};
  const effortLabels = ["", "Too easy", "Moderate", "Hard", "Max effort"];
  const sorenessLabels = ["", "Fresh", "A little sore", "Pretty sore", "Beat up"];

  function startEdit() {
    const initial: Record<string, { reps: string; weight: string }[]> = {};
    Object.entries(logs).forEach(([key, ex]) => {
      initial[key] = ex.actual.map((s) => ({ reps: s.reps, weight: s.weight }));
    });
    setEditLogs(initial);
    setEditing(true);
  }

  function saveEdits() {
    // Update the session in progressDB
    const updatedSessions = progressDB.sessions.map((s: unknown) => {
      const sess = s as { weekNum?: number; dayIdx?: number; logs?: Record<number, unknown> };
      if (sess.weekNum === session.weekNum && sess.dayIdx === session.dayIdx) {
        const updatedLogs = { ...sess.logs };
        Object.entries(editLogs).forEach(([key, sets]) => {
          const existing = (updatedLogs as Record<string, { name: string; actual: { reps: string; weight: string }[] }>)[key];
          if (existing) {
            (updatedLogs as Record<string, { name: string; actual: { reps: string; weight: string }[] }>)[key] = { ...existing, actual: sets };
          }
        });
        return { ...sess, logs: updatedLogs };
      }
      return s;
    });

    setProgressDB({ ...progressDB, sessions: updatedSessions });
    setEditing(false);
    toast("Session updated", "success");
  }

  return (
    <BottomSheet open={open} onClose={onClose} title={session.title || "Session Review"}>
      <div className="flex items-center gap-3 mb-4">
        <span className="text-xs text-muted2">
          Effort: <span className="text-text">{effortLabels[session.effort || 0]}</span>
        </span>
        <span className="text-xs text-muted2">
          Feeling: <span className="text-text">{sorenessLabels[session.soreness || 0]}</span>
        </span>
      </div>

      <div className="flex flex-col gap-3">
        {Object.entries(logs).map(([key, ex]) => {
          if (!ex.saved && ex.actual.length === 0) return null;
          const skipped = ex.saved && ex.actual.length === 0;

          return (
            <div key={key} className="rounded-lg border border-border bg-bg p-3">
              <p className={`text-sm font-medium mb-1.5 ${skipped ? "text-muted line-through" : "text-text"}`}>
                {ex.name}
              </p>
              {skipped ? (
                <span className="text-[10px] text-muted">Skipped</span>
              ) : editing ? (
                <div className="flex flex-col gap-1.5">
                  {(editLogs[key] || ex.actual).map((set, i) => (
                    <div key={i} className="flex items-center gap-2 text-xs">
                      <span className="text-muted w-10">Set {i + 1}</span>
                      <input
                        type="number" inputMode="numeric" placeholder="reps"
                        value={(editLogs[key]?.[i]?.reps) || ""}
                        onChange={(e) => {
                          const updated = { ...editLogs };
                          if (!updated[key]) updated[key] = ex.actual.map(s => ({ ...s }));
                          updated[key][i] = { ...updated[key][i], reps: e.target.value };
                          setEditLogs(updated);
                        }}
                        className="w-14 rounded border border-border bg-surface px-2 py-1 text-center text-xs text-text outline-none focus:border-accent"
                      />
                      <span className="text-muted">x</span>
                      <input
                        type="number" inputMode="decimal" placeholder="kg"
                        value={(editLogs[key]?.[i]?.weight) || ""}
                        onChange={(e) => {
                          const updated = { ...editLogs };
                          if (!updated[key]) updated[key] = ex.actual.map(s => ({ ...s }));
                          updated[key][i] = { ...updated[key][i], weight: e.target.value };
                          setEditLogs(updated);
                        }}
                        className="w-14 rounded border border-border bg-surface px-2 py-1 text-center text-xs text-text outline-none focus:border-accent"
                      />
                      <span className="text-[10px] text-muted">kg</span>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="flex flex-col gap-0.5">
                  {ex.actual.filter((s) => s.reps || s.weight).map((set, i) => (
                    <span key={i} className="text-xs text-muted2">
                      Set {i + 1}: {set.reps} reps x {set.weight || "BW"} kg
                    </span>
                  ))}
                </div>
              )}
              {ex.note && !editing && (
                <p className="mt-1 text-[10px] text-muted italic">{ex.note}</p>
              )}
            </div>
          );
        })}
      </div>

      <div className="mt-4 flex gap-2">
        {editing ? (
          <>
            <Button size="sm" className="flex-1" onClick={saveEdits}>Save changes</Button>
            <Button size="sm" variant="ghost" className="flex-1" onClick={() => setEditing(false)}>Cancel</Button>
          </>
        ) : (
          <Button size="sm" variant="secondary" className="w-full" onClick={startEdit}>Edit session log</Button>
        )}
      </div>
    </BottomSheet>
  );
}

// ── Helpers ──

function getWeekDateRange(): string {
  const now = new Date();
  const day = now.getDay();
  const monday = new Date(now);
  monday.setDate(now.getDate() - (day === 0 ? 6 : day - 1));
  const sunday = new Date(monday);
  sunday.setDate(monday.getDate() + 6);

  const fmt = (d: Date) =>
    d.toLocaleDateString("en-GB", { day: "numeric", month: "short" });

  return `${fmt(monday)}–${fmt(sunday)}`;
}
