"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useKineStore } from "@/store/useKineStore";
import { buildWeek } from "@/lib/week-builder";
import type { WeekData, WeekDay } from "@/lib/week-builder";
import { DAY_LABELS } from "@/data/constants";
import { getCurrentPhase } from "@/lib/cycle";
import { getCurrentPhaseInfo } from "@/lib/periodisation";
import Button from "@/components/Button";
import BottomSheet from "@/components/BottomSheet";
import SessionRearrange from "@/components/SessionRearrange";
import { toast } from "@/components/Toast";
import { findExercise } from "@/data/exercise-library";
import { weightUnit, formatDateShortLocale, detectLocale } from "@/lib/format";
import type { MuscleGroup } from "@/data/exercise-library";
import AdaptationCard from "@/components/AdaptationCard";
import RestDayHome from "@/components/RestDayHome";
import StreakMilestone from "@/components/StreakMilestone";
import Link from "next/link";

const CATEGORY_COLORS: Record<MuscleGroup, string> = {
  push: "var(--color-cat-push)",
  pull: "var(--color-cat-pull)",
  legs: "var(--color-cat-legs)",
  hinge: "var(--color-cat-hinge)",
  core: "var(--color-cat-core)",
  cardio: "var(--color-cat-cardio)",
  calisthenics: "var(--color-cat-core)",
};

function getCategoryColor(exerciseName: string): string {
  const ex = findExercise(exerciseName);
  return ex ? CATEGORY_COLORS[ex.muscle] : "var(--color-muted)";
}

const LOADING_MESSAGES = [
  "Analysing your training profile…",
  "Building your session structure…",
  "Selecting exercises for your equipment…",
  "Balancing volume and recovery…",
  "Finalising your programme…",
];

export default function AppHome() {
  const { weekData, setWeekData, goal, progressDB } = useKineStore();
  const [loading, setLoading] = useState(false);
  const [loadingMsg, setLoadingMsg] = useState(0);
  const router = useRouter();

  // If no goal set, redirect to onboarding
  useEffect(() => {
    if (!goal) {
      router.replace("/app/onboarding");
    }
  }, [goal, router]);

  // Rotate loading messages
  useEffect(() => {
    if (!loading) return;
    const interval = setInterval(() => {
      setLoadingMsg((prev) => (prev + 1) % LOADING_MESSAGES.length);
    }, 3000);
    return () => clearInterval(interval);
  }, [loading]);

  async function handleBuildWeek() {
    setLoading(true);
    setLoadingMsg(0);

    const result = await buildWeek();

    if (result.weekData) {
      setWeekData(result.weekData);
    }

    if (!result.success && result.error) {
      toast(result.error, "error");
    }

    setLoading(false);
  }

  if (!goal) return null;

  // No week data yet — show build prompt
  if (!weekData) {
    return (
      <div className="flex min-h-[60vh] flex-col items-center justify-center text-center">
        {loading ? (
          <div role="status" aria-label="Building your week">
            <div className="h-8 w-8 animate-spin rounded-full border-2 border-accent border-t-transparent" aria-hidden="true" />
            <p className="mt-4 text-sm text-muted2 animate-pulse" aria-live="polite">
              {LOADING_MESSAGES[loadingMsg]}
            </p>
          </div>
        ) : (
          <>
            <h2 className="font-display text-2xl tracking-wide text-text">
              Ready to build your week
            </h2>
            <p className="mt-2 text-sm text-muted2">
              Your personalised training programme will be generated by AI.
            </p>
            <Button className="mt-6" size="lg" onClick={handleBuildWeek}>
              Build Week {progressDB.currentWeek || 1} →
            </Button>
          </>
        )}
      </div>
    );
  }

  // Show week view
  const week = weekData as WeekData;

  return <WeekView week={week} onRebuild={handleBuildWeek} loading={loading} />;
}

// ── Cycle Phase Colors ──

const PHASE_COLORS: Record<string, string> = {
  menstrual: "#b05a5a",
  follicular: "#6a9a7a",
  ovulatory: "#C49098",
  luteal: "#8a7a5a",
};

// ── Cycle Arc Bar ──

function CycleArc({ cycleDay, cycleLength, logCount }: { cycleDay: number; cycleLength: number; logCount: number }) {
  const L = cycleLength;
  const mEnd = 5;
  const fEnd = Math.round(L * 0.46);
  const oEnd = Math.round(L * 0.54);
  const segs = [
    { phase: "menstrual", days: mEnd },
    { phase: "follicular", days: fEnd - mEnd },
    { phase: "ovulatory", days: oEnd - fEnd },
    { phase: "luteal", days: L - oEnd },
  ];
  const pct = Math.min(((cycleDay - 1) / L) * 100, 99);

  return (
    <div>
      <p className="font-display text-[9px] tracking-[2px] text-muted uppercase mb-1.5">
        {logCount >= 2 ? `${L}-day cycle` : "Cycle (28-day default)"}
      </p>
      <div className="relative flex h-1 gap-0.5 rounded-sm">
        {segs.map((s) => (
          <div
            key={s.phase}
            className="rounded-sm"
            style={{ flex: s.days, background: PHASE_COLORS[s.phase] }}
          />
        ))}
        <div
          className="absolute rounded-sm"
          style={{
            top: "-3px",
            left: `calc(${pct}% - 1px)`,
            width: "2px",
            height: "10px",
            background: "white",
            opacity: 0.9,
          }}
        />
      </div>
    </div>
  );
}

// ── Week View ──

function WeekView({
  week,
  onRebuild,
  loading,
}: {
  week: WeekData;
  onRebuild: () => void;
  loading: boolean;
}) {
  const { cycleType, cycle, setCycle, progressDB, weekHistory, exp } = useKineStore();
  const [showRearrange, setShowRearrange] = useState(false);
  const [viewingPastIdx, setViewingPastIdx] = useState<number | null>(null);
  const today = new Date().getDay();
  const todayIdx = today === 0 ? 6 : today - 1;
  const weekStart = getWeekDateRange();
  const trainingPhase = getCurrentPhaseInfo(progressDB.currentWeek, progressDB.phaseOffset);

  // Week navigation: past weeks from history, current week is live
  const isViewingPast = viewingPastIdx !== null;
  const displayWeek = isViewingPast
    ? (weekHistory[viewingPastIdx] as WeekData)
    : week;
  const displayWeekNum = displayWeek?._weekNum || 1;
  const hasPrev = isViewingPast ? viewingPastIdx > 0 : weekHistory.length > 0;
  const hasNext = isViewingPast; // can always go forward to current

  function goToPrevWeek() {
    if (isViewingPast && viewingPastIdx > 0) {
      setViewingPastIdx(viewingPastIdx - 1);
    } else if (!isViewingPast && weekHistory.length > 0) {
      setViewingPastIdx(weekHistory.length - 1);
    }
  }

  function goToNextWeek() {
    if (isViewingPast) {
      if (viewingPastIdx < weekHistory.length - 1) {
        setViewingPastIdx(viewingPastIdx + 1);
      } else {
        setViewingPastIdx(null); // back to current
      }
    }
  }

  // Cycle phase
  const phase = cycleType === "regular"
    ? getCurrentPhase(cycle.periodLog, cycle.avgLength)
    : null;

  if (!displayWeek) return null;

  return (
    <div>
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            {hasPrev && (
              <button onClick={goToPrevWeek} className="text-muted2 hover:text-accent transition-colors text-sm">
                ‹
              </button>
            )}
            <p className="text-[10px] tracking-[0.3em] text-accent uppercase">
              Week {displayWeekNum}{isViewingPast ? "" : ` · ${weekStart}`}
            </p>
            {hasNext && (
              <button onClick={goToNextWeek} className="text-muted2 hover:text-accent transition-colors text-sm">
                ›
              </button>
            )}
            {isViewingPast && (
              <button onClick={() => setViewingPastIdx(null)}
                className="text-[9px] text-accent border border-accent/30 rounded-full px-2 py-0.5 hover:bg-accent/10 transition-all">
                Current →
              </button>
            )}
          </div>
          <Link href="/app/calendar" className="text-[10px] text-muted2 hover:text-accent transition-colors">
            Calendar →
          </Link>
        </div>
        <h1 className="mt-1 font-display text-2xl tracking-wide text-text">
          Your Week
        </h1>
        {displayWeek._isFallback && (
          <p className="mt-1 text-[10px] text-muted uppercase tracking-wider">
            Standard programme — AI will personalise next time
          </p>
        )}
        <div className="mt-1 flex items-center gap-2">
          <span className="rounded-full bg-surface2 px-2 py-0.5 text-[10px] text-muted2">
            {trainingPhase.label} · Week {trainingPhase.blockWeek}/3
          </span>
        </div>
      </div>

      {/* Cycle phase arc + period quick-log */}
      {phase && (
        <div className="mb-4 rounded-[14px] border border-border bg-surface p-4">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <span className="inline-block w-[7px] h-[7px] rounded-full shrink-0" style={{ background: PHASE_COLORS[phase.phase] }} />
              <span className="text-xs font-medium" style={{ color: PHASE_COLORS[phase.phase] }}>
                Day {phase.day}
              </span>
              <span className="text-[10px] text-muted2">{phase.label} phase</span>
            </div>
            <button
              onClick={() => {
                const today = new Date().toISOString().split("T")[0];
                const lastLog = cycle.periodLog[cycle.periodLog.length - 1];
                const type = lastLog?.type === "start" ? "end" : "start";
                setCycle({
                  ...cycle,
                  periodLog: [...cycle.periodLog, { date: today, type }],
                });
                toast(`Period ${type} logged`, "success");
              }}
              className="text-[10px] text-accent hover:underline"
            >
              Log period {cycle.periodLog[cycle.periodLog.length - 1]?.type === "start" ? "end" : "start"}
            </button>
          </div>

          {/* Cycle arc bar */}
          <CycleArc cycleDay={phase.day} cycleLength={cycle.avgLength || 28} logCount={cycle.periodLog.filter(p => p.type === "start").length} />

          <p className="mt-3 text-[10px] text-muted2 font-light leading-relaxed">{phase.trainingNote}</p>
        </div>
      )}
      {/* Period quick-log when no cycle phase (cycle type is regular but no log yet) */}
      {cycleType === "regular" && !phase && (
        <div className="mb-4 rounded-[var(--radius-default)] border border-border/50 bg-surface/50 p-3">
          <div className="flex items-center justify-between">
            <span className="text-xs text-muted2">No period logged yet</span>
            <button
              onClick={() => {
                const today = new Date().toISOString().split("T")[0];
                setCycle({
                  ...cycle,
                  periodLog: [...cycle.periodLog, { date: today, type: "start" }],
                });
                toast("Period start logged", "success");
              }}
              className="text-[10px] text-accent hover:underline"
            >
              Log period start
            </button>
          </div>
        </div>
      )}

      {/* Adaptation card — surfaces why this week looks the way it does */}
      {!isViewingPast && <AdaptationCard />}

      {/* Rest day home — shows cycle insight, tomorrow preview, form tip */}
      {!isViewingPast && displayWeek.days[todayIdx]?.isRest && (
        <RestDayHome week={displayWeek} todayIdx={todayIdx} />
      )}

      {/* Coach note */}
      {displayWeek.weekCoachNote && (
        <div className="mb-6 rounded-[var(--radius-default)] border border-border bg-surface p-4">
          <p className="text-xs leading-relaxed text-muted2">
            {displayWeek.weekCoachNote}
          </p>
        </div>
      )}

      {/* Gap reentry */}
      {(() => {
        const lastSession = (progressDB.sessions as { date?: string }[]).slice(-1)[0];
        if (lastSession?.date) {
          const daysSince = Math.floor((Date.now() - new Date(lastSession.date).getTime()) / (1000 * 60 * 60 * 24));
          if (daysSince >= 7) {
            return (
              <div className="mb-4 rounded-[var(--radius-default)] border border-accent/30 bg-accent-dim p-4">
                <p className="text-sm font-medium text-text">Welcome back</p>
                <p className="text-xs text-muted2 mt-1">
                  It&apos;s been {daysSince} days. {progressDB.sessions.length} session{progressDB.sessions.length > 1 ? "s" : ""} completed so far.
                  No guilt — just pick up where you left off.
                </p>
              </div>
            );
          }
          if (daysSince >= 4) {
            return (
              <div className="mb-4 rounded-[var(--radius-default)] border border-border bg-surface p-3">
                <p className="text-xs text-muted2">
                  {daysSince} days since your last session. Ready when you are.
                </p>
              </div>
            );
          }
        }
        return null;
      })()}

      {/* Past week banner */}
      {isViewingPast && (
        <div className="mb-4 rounded-lg border border-muted/20 bg-surface/50 px-4 py-3 text-center">
          <p className="text-[10px] text-muted2">Viewing Week {displayWeekNum} · read-only</p>
        </div>
      )}

      {/* Session completion summary — current week only */}
      {!isViewingPast && (() => {
        const weekSessions = (progressDB.sessions as { weekNum?: number }[])
          .filter((s) => s.weekNum === progressDB.currentWeek);
        const trainingDayCount = displayWeek.days.filter((d) => !d.isRest).length;
        if (weekSessions.length > 0 && weekSessions.length < trainingDayCount) {
          return (
            <p className="mb-3 text-xs text-muted2">
              {weekSessions.length}/{trainingDayCount} sessions done this week
            </p>
          );
        }
        if (weekSessions.length >= trainingDayCount && trainingDayCount > 0) {
          const WEEK_COMPLETE_MESSAGES = [
            "Consistency beats intensity. You showed up.",
            "Another week in the book. That's how progress works.",
            "You did the work. Let recovery do the rest.",
            "Week done. Strength isn't built in a day — it's built in weeks like this.",
          ];
          const msg = WEEK_COMPLETE_MESSAGES[(progressDB.currentWeek - 1) % WEEK_COMPLETE_MESSAGES.length];
          return (
            <div className="mb-5 rounded-[14px] border border-accent/40 bg-accent-dim p-5 text-center animate-celebrate">
              <p className="font-display text-[11px] tracking-[3px] text-accent uppercase mb-1">Week {progressDB.currentWeek} complete</p>
              <p className="font-display text-xl tracking-wide text-text">
                {weekSessions.length} sessions done
              </p>
              <p className="mt-2 text-[11px] text-muted2 font-light leading-relaxed max-w-[280px] mx-auto">
                {msg}
              </p>
            </div>
          );
        }
        return null;
      })()}

      {/* Programme-week streak and journey milestones */}
      {!isViewingPast && <StreakMilestone />}

      {/* Days */}
      {(() => {
        const viewWeekNum = isViewingPast ? displayWeekNum : progressDB.currentWeek;

        // Find next active session (current week only)
        const nextActiveIdx = isViewingPast ? -1 : displayWeek.days.findIndex((d, i) => {
          if (d.isRest) return false;
          const completed = (progressDB.sessions as { weekNum?: number; dayIdx?: number }[])
            .some((s) => s.weekNum === progressDB.currentWeek && s.dayIdx === i);
          return !completed && i >= todayIdx;
        });

        return (
          <div className="flex flex-col gap-2">
            {displayWeek.days.map((day, i) => {
              const isCompleted = (progressDB.sessions as { weekNum?: number; dayIdx?: number }[])
                .some((s) => s.weekNum === viewWeekNum && s.dayIdx === i);

              return (
                <DayCard
                  key={i} day={day} dayIdx={i}
                  isToday={!isViewingPast && i === todayIdx}
                  isCompleted={isCompleted}
                  isPast={isViewingPast || i < todayIdx}
                  expanded={!isViewingPast && (i === nextActiveIdx || i === todayIdx)}
                  readOnly={isViewingPast}
                />
              );
            })}
          </div>
        );
      })()}

      {/* Next week preview — show when all sessions complete */}
      {(() => {
        const weekSessions = (progressDB.sessions as { weekNum?: number }[])
          .filter((s) => s.weekNum === progressDB.currentWeek);
        const trainingDayCount = displayWeek.days.filter((d) => !d.isRest).length;
        if (weekSessions.length >= trainingDayCount && trainingDayCount > 0) {
          const nextWeekNum = (progressDB.currentWeek || 1) + 1;
          const nextPhase = getCurrentPhaseInfo(nextWeekNum, progressDB.phaseOffset);
          return (
            <div className="mt-6 rounded-[14px] border border-border/50 bg-surface/50 p-4 text-center">
              <p className="font-display text-[9px] tracking-[2px] text-muted uppercase mb-1">Up next</p>
              <p className="font-display text-lg tracking-wide text-text">
                Week {nextWeekNum}
              </p>
              <p className="mt-1 text-[10px] text-muted2">
                {nextPhase.label} · {nextPhase.description}
              </p>
              <Button variant="secondary" size="sm" className="mt-3" onClick={onRebuild} disabled={loading}>
                Build Week {nextWeekNum} →
              </Button>
            </div>
          );
        }
        return null;
      })()}

      {/* Actions */}
      <div className="mt-8 flex flex-wrap justify-center gap-3">
        <Link href="/app/week-checkin" className="inline-flex items-center rounded-[var(--radius-default)] px-3 py-1.5 text-xs text-muted2 hover:text-text hover:bg-surface2 transition-all">
          Check-in
        </Link>
        <Button variant="ghost" size="sm" onClick={() => setShowRearrange(true)}>
          Rearrange
        </Button>
        <Button variant="ghost" size="sm" onClick={onRebuild} disabled={loading}>
          {loading ? "Rebuilding…" : "Regenerate"}
        </Button>
        <Link href="/app/sandbox" className="inline-flex items-center rounded-[var(--radius-default)] px-3 py-1.5 text-xs text-muted2 hover:text-text hover:bg-surface2 transition-all">
          Design Week
        </Link>
      </div>

      <SessionRearrange open={showRearrange} onClose={() => setShowRearrange(false)} />

      {/* Health disclaimer */}
      <p className="mt-6 text-center text-[10px] text-muted leading-relaxed">
        Kinē provides fitness guidance, not medical advice.
        Consult your doctor before starting any exercise programme.
      </p>

      {/* Dev tools — inline, remove before production launch */}
      <DevTools onRebuild={onRebuild} loading={loading} />
    </div>
  );
}

// ── Dev Tools (inline) ──

function DevTools({ onRebuild, loading }: { onRebuild: () => void; loading: boolean }) {
  const [open, setOpen] = useState(false);
  const store = useKineStore();

  function advanceWeek() {
    store.setProgressDB({
      ...store.progressDB,
      currentWeek: store.progressDB.currentWeek + 1,
    });
    store.setWeekData(null);
    toast(`Advanced to Week ${store.progressDB.currentWeek + 1}`, "success");
  }

  function simulatePerfectWeek() {
    const planned = parseInt(store.days || "3");
    const sessions = [...store.progressDB.sessions];
    for (let i = 0; i < planned; i++) {
      sessions.push({
        dayIdx: i,
        date: new Date().toISOString().split("T")[0],
        weekNum: store.progressDB.currentWeek,
        title: `Session ${i + 1}`,
        logs: {},
        effort: 2,
        soreness: 1,
        prs: [],
      });
    }
    store.setProgressDB({ ...store.progressDB, sessions });
    toast("Perfect week simulated", "success");
  }

  function resetAll() {
    if (confirm("Reset ALL data?")) {
      localStorage.removeItem("kine_v2");
      window.location.href = "/app/onboarding";
    }
  }

  return (
    <div className="mt-10 border-t border-border/30 pt-4">
      <button
        onClick={() => setOpen(!open)}
        className="w-full text-center text-[10px] text-muted hover:text-muted2 transition-colors"
      >
        {open ? "▾ Hide dev tools" : "▸ Dev tools"}
      </button>
      {open && (
        <div className="mt-3 rounded-xl border border-amber-400/20 bg-surface/50 p-4 flex flex-col gap-2">
          <p className="text-[9px] text-amber-400 tracking-wider uppercase mb-1">Testing only — remove before launch</p>
          <div className="text-[10px] text-muted2 mb-2">
            Week {store.progressDB.currentWeek} · {store.progressDB.sessions.length} sessions logged
          </div>
          <button onClick={advanceWeek}
            className="w-full rounded-lg border border-border bg-surface px-3 py-2 text-xs text-text hover:border-accent transition-all">
            Advance to Week {store.progressDB.currentWeek + 1}
          </button>
          <button onClick={simulatePerfectWeek}
            className="w-full rounded-lg border border-border bg-surface px-3 py-2 text-xs text-text hover:border-accent transition-all">
            Simulate perfect week
          </button>
          <button onClick={() => { advanceWeek(); setTimeout(onRebuild, 100); }}
            className="w-full rounded-lg border border-accent/30 bg-accent-dim px-3 py-2 text-xs text-accent hover:bg-accent/20 transition-all"
            disabled={loading}>
            {loading ? "Building…" : `⚡ Skip to Week ${store.progressDB.currentWeek + 1} & build`}
          </button>
          <button onClick={resetAll}
            className="w-full rounded-lg border border-red-400/20 px-3 py-2 text-xs text-red-400 hover:bg-red-400/10 transition-all">
            Reset all data
          </button>
        </div>
      )}
    </div>
  );
}

// ── Day Card ──

// ── Rest day recovery messages ──
const REST_DAY_MESSAGES = [
  "Your muscles grow during rest, not during training.",
  "Recovery is where the work becomes results.",
  "Active recovery — a walk, stretch, or gentle movement helps.",
  "Sleep and nutrition do the heavy lifting today.",
  "Rest days prevent injury and keep you consistent long-term.",
  "Trust the process — rest is part of the programme.",
];

function getRestMessage(dayIdx: number): string {
  return REST_DAY_MESSAGES[dayIdx % REST_DAY_MESSAGES.length];
}

function DayCard({ day, dayIdx, isToday, isCompleted = false, isPast = false, expanded = false, readOnly = false }: {
  day: WeekDay; dayIdx: number; isToday: boolean; isCompleted?: boolean; isPast?: boolean; expanded?: boolean; readOnly?: boolean;
}) {
  const router = useRouter();
  const { progressDB, setProgressDB } = useKineStore();
  const [showSessionReview, setShowSessionReview] = useState(false);
  const dayLabel = DAY_LABELS[(day.dayNumber - 1) % 7];

  // Find completed session log for this day
  const completedSession = isCompleted
    ? (progressDB.sessions as { weekNum?: number; dayIdx?: number; logs?: Record<number, { name: string; actual: { reps: string; weight: string }[]; note?: string; saved?: boolean }>; effort?: number; soreness?: number; title?: string }[])
        .find((s) => s.weekNum === progressDB.currentWeek && s.dayIdx === dayIdx)
    : null;

  if (day.isRest) {
    return (
      <div
        className={`rounded-[14px] border px-[18px] py-3 transition-all ${
          isToday ? "border-accent/30 bg-accent-dim"
          : isPast ? "border-border/30 bg-surface/30 opacity-60"
          : "border-border/50 bg-surface/50"
        }`}
      >
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-xs font-medium text-muted2">{dayLabel}</span>
            {isToday && (
              <span className="rounded-full bg-accent/20 px-2 py-0.5 text-[10px] text-accent">
                Today
              </span>
            )}
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs text-muted">Rest & Recovery</span>
            {!isPast && (
              <button
                onClick={() => router.push(`/app/custom-builder?day=${dayIdx}`)}
                className="text-[10px] text-muted2 hover:text-accent transition-colors"
              >
                + add session
              </button>
            )}
          </div>
        </div>
        {/* #9: Rest day recovery message */}
        {(isToday || (!isPast && expanded)) && (
          <p className="mt-2 text-[10px] text-muted font-light leading-relaxed">
            {getRestMessage(dayIdx)}
          </p>
        )}
      </div>
    );
  }

  return (
    <div
      className={`rounded-[14px] border p-[18px] transition-all active:scale-[0.98] ${
        isCompleted ? "border-accent/30 bg-accent-dim/30"
        : isToday ? "border-accent bg-surface"
        : isPast ? "border-border/50 bg-surface/50 opacity-60"
        : "border-border bg-surface hover:border-border-active"
      }`}
    >
      {/* Day header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-xs font-medium text-muted2">{dayLabel}</span>
          {isToday && (
            <span className="rounded-full bg-accent/20 px-2.5 py-0.5 text-[10px] font-medium text-accent tracking-wide">
              Today
            </span>
          )}
          {isCompleted && (
            <span className="rounded-full bg-accent/20 px-2.5 py-0.5 text-[10px] font-medium text-accent tracking-wide">
              ✓ done
            </span>
          )}
        </div>
        <span className="font-display text-[9px] tracking-[2px] text-muted uppercase">{day.sessionDuration}</span>
      </div>

      {/* Title */}
      <h3 className="mt-2 font-display text-lg tracking-wide text-text" style={{ fontSize: 'clamp(18px, 5vw, 22px)' }}>
        {day.sessionTitle}
      </h3>

      {/* Collapsed: summary with context */}
      {!expanded && (
        <div className="mt-1.5">
          <div className="flex items-center justify-between">
            <p className="text-[11px] text-muted2 font-light truncate flex-1">
              {day.exercises.length} exercises · {day.sessionDuration}
            </p>
            {!readOnly && (
              <button onClick={() => router.push(`/app/pre-session?day=${dayIdx}`)}
                className="text-[10px] text-accent hover:underline shrink-0 ml-2">View →</button>
            )}
          </div>
          {day.coachNote && (
            <p className="mt-1.5 text-[10px] text-muted font-light leading-relaxed truncate">{day.coachNote}</p>
          )}
          <div className="mt-2 flex flex-wrap gap-1">
            {day.exercises.slice(0, 3).map((ex, i) => (
              <span key={i} className="inline-flex items-center gap-1 text-[9px] text-muted2 bg-surface2/50 rounded px-1.5 py-0.5">
                <span className="inline-block w-1.5 h-1.5 rounded-full shrink-0" style={{ background: getCategoryColor(ex.name) }} />
                {ex.name}
              </span>
            ))}
            {day.exercises.length > 3 && (
              <span className="text-[9px] text-muted">+{day.exercises.length - 3}</span>
            )}
          </div>
        </div>
      )}

      {/* Expanded: full details */}
      {expanded && (
        <>
          {day.coachNote && <p className="mt-1.5 text-xs text-muted2 leading-relaxed">{day.coachNote}</p>}
          <div className="mt-3 flex flex-col gap-1.5">
            {day.exercises.map((ex, i) => (
              <div key={i} className="flex items-center justify-between text-xs">
                <span className="flex items-center gap-1.5 text-text/80">
                  <span className="inline-block w-1.5 h-1.5 rounded-full shrink-0" style={{ background: getCategoryColor(ex.name) }} />
                  {ex.name}
                </span>
                <span className="text-muted font-light">{ex.sets}×{ex.reps}</span>
              </div>
            ))}
          </div>
          <div className="mt-4 flex gap-2">
            {isCompleted ? (
              <>
                <Button className="flex-1" size="sm" variant="secondary"
                  onClick={() => setShowSessionReview(true)}>
                  View results
                </Button>
                <Button className="flex-1" size="sm" variant="ghost"
                  onClick={() => router.push(`/app/pre-session?day=${dayIdx}`)}>
                  Redo
                </Button>
              </>
            ) : (
              <Button className="w-full" size="sm" variant={isToday ? "primary" : "secondary"}
                onClick={() => router.push(`/app/pre-session?day=${dayIdx}`)}>
                {isToday ? "Start session" : "View session"}
              </Button>
            )}
          </div>
        </>
      )}

      {/* #6: Session replay/amendment bottom sheet */}
      {completedSession && (
        <SessionReviewSheet
          open={showSessionReview}
          onClose={() => setShowSessionReview(false)}
          session={completedSession}
          dayIdx={dayIdx}
        />
      )}
    </div>
  );
}

// ── Session Review/Edit Sheet ──

function SessionReviewSheet({ open, onClose, session, dayIdx }: {
  open: boolean;
  onClose: () => void;
  session: { logs?: Record<number, { name: string; actual: { reps: string; weight: string }[]; note?: string; saved?: boolean }>; effort?: number; soreness?: number; title?: string; weekNum?: number; dayIdx?: number };
  dayIdx: number;
}) {
  const { progressDB, setProgressDB, measurementSystem } = useKineStore();
  const unit = weightUnit(measurementSystem || "metric");
  const [editing, setEditing] = useState(false);
  const [editLogs, setEditLogs] = useState<Record<string, { reps: string; weight: string }[]>>({});

  const logs = session.logs || {};
  const effortLabels = ["", "Too easy", "Moderate", "Hard", "Max effort"];
  const sorenessLabels = ["", "Fresh", "A little sore", "Pretty sore", "Beat up"];

  function startEdit() {
    const initial: Record<string, { reps: string; weight: string }[]> = {};
    Object.entries(logs).forEach(([key, ex]) => {
      initial[key] = ex.actual.map((s) => ({ reps: s.reps, weight: s.weight }));
    });
    setEditLogs(initial);
    setEditing(true);
  }

  function saveEdits() {
    // Update the session in progressDB
    const updatedSessions = progressDB.sessions.map((s) => {
      const sess = s as { weekNum?: number; dayIdx?: number; logs?: Record<number, unknown> };
      if (sess.weekNum === session.weekNum && sess.dayIdx === session.dayIdx) {
        const updatedLogs = { ...sess.logs };
        Object.entries(editLogs).forEach(([key, sets]) => {
          const existing = (updatedLogs as Record<string, { name: string; actual: { reps: string; weight: string }[] }>)[key];
          if (existing) {
            (updatedLogs as Record<string, { name: string; actual: { reps: string; weight: string }[] }>)[key] = { ...existing, actual: sets };
          }
        });
        return { ...sess, logs: updatedLogs };
      }
      return s;
    });

    setProgressDB({ ...progressDB, sessions: updatedSessions });
    setEditing(false);
    toast("Session updated", "success");
  }

  return (
    <BottomSheet open={open} onClose={onClose} title={session.title || "Session Review"}>
      <div className="flex items-center gap-3 mb-4">
        <span className="text-xs text-muted2">
          Effort: <span className="text-text">{effortLabels[session.effort || 0]}</span>
        </span>
        <span className="text-xs text-muted2">
          Feeling: <span className="text-text">{sorenessLabels[session.soreness || 0]}</span>
        </span>
      </div>

      <div className="flex flex-col gap-3">
        {Object.entries(logs).map(([key, ex]) => {
          if (!ex.saved && ex.actual.length === 0) return null;
          const skipped = ex.saved && ex.actual.length === 0;

          return (
            <div key={key} className="rounded-lg border border-border bg-bg p-3">
              <p className={`text-sm font-medium mb-1.5 ${skipped ? "text-muted line-through" : "text-text"}`}>
                {ex.name}
              </p>
              {skipped ? (
                <span className="text-[10px] text-muted">Skipped</span>
              ) : editing ? (
                <div className="flex flex-col gap-1.5">
                  {(editLogs[key] || ex.actual).map((set, i) => (
                    <div key={i} className="flex items-center gap-2 text-xs">
                      <span className="text-muted w-10">Set {i + 1}</span>
                      <input
                        type="number" inputMode="numeric" placeholder="reps"
                        value={(editLogs[key]?.[i]?.reps) || ""}
                        onChange={(e) => {
                          const updated = { ...editLogs };
                          if (!updated[key]) updated[key] = ex.actual.map(s => ({ ...s }));
                          updated[key][i] = { ...updated[key][i], reps: e.target.value };
                          setEditLogs(updated);
                        }}
                        className="w-14 rounded border border-border bg-surface px-2 py-1 text-center text-xs text-text outline-none focus:border-accent"
                      />
                      <span className="text-muted">x</span>
                      <input
                        type="number" inputMode="decimal" placeholder={unit}
                        value={(editLogs[key]?.[i]?.weight) || ""}
                        onChange={(e) => {
                          const updated = { ...editLogs };
                          if (!updated[key]) updated[key] = ex.actual.map(s => ({ ...s }));
                          updated[key][i] = { ...updated[key][i], weight: e.target.value };
                          setEditLogs(updated);
                        }}
                        className="w-14 rounded border border-border bg-surface px-2 py-1 text-center text-xs text-text outline-none focus:border-accent"
                      />
                      <span className="text-[10px] text-muted">{unit}</span>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="flex flex-col gap-0.5">
                  {ex.actual.filter((s) => s.reps || s.weight).map((set, i) => (
                    <span key={i} className="text-xs text-muted2">
                      Set {i + 1}: {set.reps} reps x {set.weight || "BW"} {unit}
                    </span>
                  ))}
                </div>
              )}
              {ex.note && !editing && (
                <p className="mt-1 text-[10px] text-muted italic">{ex.note}</p>
              )}
            </div>
          );
        })}
      </div>

      <div className="mt-4 flex gap-2">
        {editing ? (
          <>
            <Button size="sm" className="flex-1" onClick={saveEdits}>Save changes</Button>
            <Button size="sm" variant="ghost" className="flex-1" onClick={() => setEditing(false)}>Cancel</Button>
          </>
        ) : (
          <Button size="sm" variant="secondary" className="w-full" onClick={startEdit}>Edit session log</Button>
        )}
      </div>
    </BottomSheet>
  );
}

// ── Helpers ──

function getWeekDateRange(): string {
  const now = new Date();
  const day = now.getDay();
  const monday = new Date(now);
  monday.setDate(now.getDate() - (day === 0 ? 6 : day - 1));
  const sunday = new Date(monday);
  sunday.setDate(monday.getDate() + 6);

  const locale = detectLocale();
  const fmt = (d: Date) =>
    d.toLocaleDateString(locale, { day: "numeric", month: "short" });

  return `${fmt(monday)}–${fmt(sunday)}`;
}
