import type { Metadata } from "next";
import ForceLightMode from "@/components/ForceLightMode";

export const metadata: Metadata = {
  title: "Terms of Service — KINĒ",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg font-body text-text px-6 py-12 max-w-2xl mx-auto">
      <ForceLightMode />
      <a href="/" className="text-xs text-muted2 hover:text-text transition-colors">
        ← Back to homepage
      </a>

      <h1 className="mt-8 font-display text-3xl tracking-wide">Terms of Service</h1>
      <p className="mt-2 text-xs text-muted2">Last updated: 26 March 2026</p>

      <div className="mt-8 space-y-6 text-sm text-muted2 leading-relaxed">
        <section>
          <h2 className="text-base font-medium text-text mb-2">1. About Kinē</h2>
          <p>
            Kinē (&quot;the Service&quot;) is an AI-powered fitness training platform operated by Kinē Ltd
            (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;). By creating an account or using the Service,
            you agree to these Terms. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-text mb-2">2. Eligibility</h2>
          <p>
            You must be at least 18 years old to use Kinē. By using the Service, you represent
            that you are at least 18 and have the legal capacity to enter into these Terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-text mb-2">3. Account &amp; Access</h2>
          <p>
            You are responsible for maintaining the confidentiality of your login credentials.
            You may not share your account or access code with others. We reserve the right to
            suspend or terminate accounts that violate these Terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-text mb-2">4. Subscriptions &amp; Billing</h2>
          <p>
            Kinē offers monthly and yearly subscription plans. Current pricing is shown on the{" "}
            <a href="/pricing" className="text-accent hover:underline">pricing page</a>.
            All subscriptions are billed in advance and renew automatically unless cancelled.
            You may cancel at any time from your profile — access continues until the end of
            your current billing period.
          </p>
          <p className="mt-2">
            We offer a 14-day money-back guarantee from the date of your first payment. To
            request a refund within this period, contact us at support@kinefit.app.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-text mb-2">5. Not Medical Advice</h2>
          <p>
            Kinē provides fitness programming and educational content. It is not a substitute
            for professional medical advice, diagnosis, or treatment. Always consult a qualified
            healthcare provider before starting any exercise programme, particularly if you have
            existing health conditions. You use the Service at your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-text mb-2">6. AI-Generated Content</h2>
          <p>
            Training programmes, coaching feedback, and exercise suggestions are generated by
            artificial intelligence. While we strive for accuracy and safety, AI-generated content
            may occasionally contain errors. You should exercise your own judgement when following
            any programme recommendation.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-text mb-2">7. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="mt-2 list-disc pl-5 space-y-1">
            <li>Reverse-engineer, scrape, or attempt to extract the AI prompts or training logic</li>
            <li>Share or redistribute generated programmes commercially</li>
            <li>Use the Service in any way that could harm other users or the platform</li>
            <li>Circumvent access controls, authentication, or billing mechanisms</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-medium text-text mb-2">8. Intellectual Property</h2>
          <p>
            All content, design, branding, exercise education, and software comprising Kinē are
            owned by Kinē Ltd. Your subscription grants you a personal, non-transferable licence
            to use the Service. You retain ownership of any personal data you provide.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-text mb-2">9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Kinē Ltd is not liable for any indirect,
            incidental, or consequential damages arising from your use of the Service, including
            but not limited to physical injury, data loss, or missed training outcomes.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-text mb-2">10. Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time. We will notify you of material changes
            via email or in-app notice. Continued use of the Service after changes constitutes
            acceptance of the updated Terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-text mb-2">11. Governing Law</h2>
          <p>
            These Terms are governed by the laws of England and Wales. Any disputes shall be
            subject to the exclusive jurisdiction of the courts of England and Wales.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-text mb-2">12. Contact</h2>
          <p>
            For questions about these Terms, contact us at{" "}
            <a href="mailto:support@kinefit.app" className="text-accent hover:underline">
              support@kinefit.app
            </a>.
          </p>
        </section>
      </div>

      <div className="mt-12 border-t border-border pt-6 text-xs text-muted">
        <p>© 2026 Kinē Ltd. All rights reserved.</p>
      </div>
    </div>
  );
}
